### PR TITLE
Bugfix/issue 84 - Support to solidity 0.8.0

### PR DESCRIPTION
**Pull request by joaquin-alfaro**
### What does this PR do?
Fixes issue when generating java classes using pragma 0.8.0

### Where should the reviewer start?
from the opened issue #84 

### Why is it needed?
It is needed to generate the code of smart contracts using pragma 0.8.0 or superior.

### CODE REVIEW

**Review by xaviarias — APPROVED** [review]

**Comment by tmac2yt** [comment]
Hi,I'm facing the same issue with you.Can you give me a plugin?

**Comment by tmac2yt** [comment]
Hi,when will the offical update the latest version on Maven repository that fix this issue. @xaviarias

**Comment by gsmorag** [comment]
When is it going to be released?

**Comment by gtebrean** [comment]
Thanks for fix! I added to https://github.com/web3j/web3j-maven-plugin/pull/89 and will release soon.

**Comment by andrii-kl** [comment]
https://github.com/web3j/web3j-maven-plugin/pull/89
the fix + tests

**Pull request closed without merging**
